services:
  - type: web
    name: VideoMateBot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: API_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false